version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Europe/London
  ignore:
  - dependency-name: "@hapi/joi"
    versions:
    - ">= 16.a, < 17"
  - dependency-name: "@hapi/joi"
    versions:
    - ">= 17.a, < 18"
  - dependency-name: query-string
    versions:
    - ">= 6.a, < 7"
  - dependency-name: axe-core
    versions:
    - 4.1.1
    - 4.1.2
    - 4.1.3
    - 4.1.4
  - dependency-name: stylelint
    versions:
    - 13.10.0
    - 13.11.0
    - 13.12.0
    - 13.9.0
  - dependency-name: "@vue/test-utils"
    versions:
    - 1.1.2
    - 1.1.3
