stages:
  - test
  - name: build
    if: branch = master AND env(TRAVIS_PULL_REQUEST) = false

# Defaults
language: node_js
node_js: '8'

# Install latest npm & dependencies
before_install: npm i -g npm@6
install: npm ci --quiet --prefer-offline

# Cache locations
cache:
  directories:
    - ~/.cache # Cypress installed into ~/.cache/Cypress
    - ~/.npm # cache npm's cache
    - ~/npm # cache latest npm

# Build stages
jobs:
  include:
    # Stage: Tests
    - stage: test
      script: npm run test-ci

    # Stage: Build & deploy (only on master)
    - stage: build
      script: npm run build-production
      after_success:
        - npm prune --production > /dev/null 2>&1
        - sh deploy/store_deploy_info.sh
        - zip -qr latest * -x .\* -x "README.md" -x assets/\* -x "gulpfile.js"
        - mkdir -p dpl_cd_upload
        - mv latest.zip dpl_cd_upload/build-$TRAVIS_BUILD_NUMBER.zip
      deploy:
      - provider: s3
        region: eu-west-1
        bucket: blf-assets
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        local_dir: public
        upload-dir: assets
        acl: public_read
        cache_control: "max-age=31536000"
        skip_cleanup: true
      - provider: s3
        region: eu-west-1
        bucket: blf-travis-test
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        local_dir: dpl_cd_upload
        skip_cleanup: true
        on:
          repo: biglotteryfund/blf-alpha
      - provider: codedeploy
        region: eu-west-1
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        bucket: blf-travis-test
        key: build-$TRAVIS_BUILD_NUMBER.zip
        bundle_type: zip
        application: BLF_Test
        deployment_group: BLF_Test_Fleet
        on:
          tags: false

# Notifications
notifications:
  slack:
    rooms:
      secure:
        raHMwe3cIkMf3lqoXOeVmTXgZ7DBneG8qddfSHXxf8EQPahCWi1gYxXlAA5xzibJlnE/C0cSCQSxhNZd/C2gXKj0abWQXWAvFW5ETdYwOYVB111THLLuTRAcADTY9QJuRC4SY3EEj6yjMgMjaDLDn2kUm1VrEafYn4nKpKxEUEe0/qtqyWi++uaauwnIH+o7YbODT/xDLTNKwi5ZWVcAFuVLWM8GbP/g/IsteV73gifx022IdXZfCcbiGk5zhXtwX2kZaHEGEkSJCxUmpCz3194yKDH0Wo/pyNaCb4yC6mbTqEAjGSaETim/s6q62U35j4G+xj7IQrsqFd9sqjr+dQMyFhPpsCKbb2mDLxnsgsc3kgru0sogdY9XGf1rlg9gYWoc3TVV8lW25R3awQNgljXKFNxJoLBCPzqYkcnbDG4eIPi9HwJAysEaFz43kzy1g3ECdbynZ9+btZGHo9u9fsnhDf68mkTDrhY2EtLJ04tlyhFo6vxbW9FsEze6apjQHmlcPPj66YJkRlp7yVY10kUh4PkjnJhvLTEDHipVO3r650h1B9mXAIqKqHIG/sf3zFBvfhDNvkjNte2w1VH5ahOarcb/ReAD604lBSvnobNEOdcbe7axCEeBY2fjYrmsxYZgKTnkrB/T+2SyugqIvo7AGbFCtcpMQY55cTPfsJM=
  webhooks:
    secure:
      'TgUaZM9PIn4u5IRDSNqHbJ8fKmKaFrbbTZzhJ2v2Ok1r7+haqlSoFjN3yN2q+HBCpy0sojbhcMEe2Me570fh63nPHFnkTPurTdhltZtcVS9ay4svgIZiseCpo/+LcSrFXuj9d5W/Faekcv14M/GHuclvovfFb+ZpVDcLkifLzTzUEp4RYG9iR1BbgvRCaPZXlg+83P61OHaLNettivoO1ut5g1pQQbWG8S6lnIbctjg0C3aU4YSWgj+lbf3EH38VfxPWDt5oGH3VMuF0KB0+tROIN5ysp8AF+I0oEp6baxKR1p5fjJ66I8mpxkB81YtVqSgCJjzeI3txvnAZFwmwzvyRbBtzITmdwafbE8svLkurqp5l3RsTyqzBzqWyVJaOPzZYSpOTbcz57i45x5EJ3qQ2ZZYcSmwCCFX67zSNy4ddRStTBCgTiIRf0/C1RCCpw4LwdhpOFnHFpWh2fPQCFa08uOMIOvqjzz+IAwsMBKuE7iNAL+7I2H4KE1Ebz3hljwPeekzGpWSHMuQKwfcMu8vBaCz/cYNV9NHw3W2/Fj4OmvIDRjzeYcdpV2QRzpKBXRp8ij+nFOAJXk7OoBJhFWDHpo26pBw80zSveqGd3fpe962vsnJrnWoqmaLlERjOm3U4WVkKhcqqYhpD7a3M33RihLl+9YoDRS44oB0G4lg='
