language: node_js
node_js:
  - '6'

before_script:
  - cd app
  - npm install -g gulp
  - npm install

script: gulp test --production

before_deploy:
  - cd ../
  - zip -qr latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/build-$TRAVIS_BUILD_NUMBER.zip

deploy:
    # first upload to s3
    - provider: s3
      region: eu-west-1
      access_key_id: AKIAJQ4UBKYUR7O4LMSQ
      secret_access_key: &1
        secure: QVmjyOcxtTqPJJyy+gIfXVYGOshkmz2A9PdYBb+RkUJypouWVDSvBfYxjMqwZmVIvhJUlgoRMI9a5oRovjLuvHDw5Mdy5TCNFtVkZx5T0jGN8L4fEDyLjNw1DveuEil4+a87r3v6Jkr05M7LbdvinYac3+OPgN2/mwD4sVRlsCqtllu1jqJX3KvyYp8G6wc/nRwcxhQz6bdMBqP1GRdNRo8ww8cDGpIGiyGTPuFF5alqDobSsGnuuQMLi/p1EUJwxW1IkNLbWMpEy2LUQi4Xs1v3XdrNwuk4xLPa5uWa4usvbEMIPC9Ma72sQOnjumdYM/7s/wMBW6qHZfd/+ONhXZPbIcG5NR5Cj1ew90Xk3cL0AkHDW8hsKMa2mllVuwCtpDlOcVeBgU3riIsc/uhKimByRVHdk+dtQM44J+HsIJCO951GcdUjQ67VbPccIeKf3lZVej6skdP7yogHIGxo/HD8pdH8DkM+CqGDKPQhSU2wUVqaPShr2Hho2THFVnqpLppC7+9AeHZbzFENEmlwXzmEC/FwKgwgMcSuUPTEpUkIWH4tkopXDtO8uYQZRjoWRnO1UDj4+8zA3iRfRUoJbz7c2Hww+MciGUgIj4Iqj3ZRXmC+6o0uIStguMJr5eGD3+mnvla9wU0SR7ZVLZv1unwwz9nl1G/+d6q95aIPUQw=
      local_dir: dpl_cd_upload
      skip_cleanup: true
      on:
        repo: biglotteryfund/blf-alpha
      bucket: blf-travis-test

    # deploy regular, minor updates to existing instances
    - provider: codedeploy
      region: eu-west-1
      access_key_id: AKIAJQ4UBKYUR7O4LMSQ
      secret_access_key: *1
      bucket: blf-travis-test
      key: build-$TRAVIS_BUILD_NUMBER.zip
      bundle_type: zip
      application: BLF_Test
      deployment_group: BLF_Test_In_Place
      on:
        tags: false

    # push major-tagged branches to brand new servers
    - provider: codedeploy
      region: eu-west-1
      access_key_id: AKIAJQ4UBKYUR7O4LMSQ
      secret_access_key: *1
      bucket: blf-travis-test
      key: build-$TRAVIS_BUILD_NUMBER.zip
      bundle_type: zip
      application: BLF_Test
      deployment_group: BLF_Test_Fleet
      on:
        tags: true
        condition: "$TRAVIS_TAG =~ ^v\d+\.\d+\.\d+$"
        all_branches: true