'use strict';

module.exports = {
    fieldAddressHistory: require('./address-history'),
    fieldBankAccountName: require('./bank-account-name'),
    fieldBankAccountNumber: require('./bank-account-number'),
    fieldBankSortCode: require('./bank-sort-code'),
    fieldBankStatement: require('./bank-statement'),
    fieldBuildingSocietyNumber: require('./building-society-number'),
    fieldCharityNumber: require('./charity-number'),
    fieldCompanyNumber: require('./company-number'),
    fieldContactLanguagePreference: require('./contact-language-preference'),
    fieldEducationNumber: require('./education-number'),
    fieldMainContactAddress: require('./main-contact-address'),
    fieldOrganisationAddress: require('./organisation-address'),
    fieldOrganisationLegalName: require('./organisation-legal-name'),
    fieldOrganisationStartDate: require('./organisation-start-date'),
    fieldOrganisationTradingName: require('./organisation-trading-name'),
    fieldOrganisationType: require('./organisation-type'),
    fieldProjectBudget: require('./project-budget'),
    fieldProjectCountry: require('./project-country'),
    fieldProjectDateRange: require('./project-date-range'),
    fieldProjectLocation: require('./project-location'),
    fieldProjectLocationDescription: require('./project-location-description'),
    fieldProjectName: require('./project-name'),
    fieldProjectPostcode: require('./project-postcode'),
    fieldProjectTotalCosts: require('./project-total-costs'),
    fieldSeniorContactAddress: require('./senior-contact-address'),
    fieldSeniorContactRole: require('./senior-contact-role'),
    fieldTotalIncomeYear: require('./total-income-year'),
    fieldYourIdeaCommunity: require('./your-idea-community'),
    fieldYourIdeaPriorities: require('./your-idea-priorities'),
    fieldYourIdeaProject: require('./your-idea-project')
};
